export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const UPDATE_PLAYER_HEALTH = "UPDATE_PLAYER_HEALTH";
export const UPDATE_PLAYER_ATTACK = "UPDATE_PLAYER_ATTACK";
export const UPDATE_PLAYER_TOKENS = "UPDATE_PLAYER_TOKENS";
export const UPDATE_CURRENT_ENEMY = "UPDATE_CURRENT_ENEMY";
export const UPDATE_ROBORTO_HEALTH = "UPDATE_ROBORTO_HEALTH";
export const UPDATE_AMY_HEALTH = "UPDATE_AMY_HEALTH";
export const UPDATE_TRUMBLE_HEALTH = "UPDATE_TRUMBLE_HEALTH";