export const UPDATE_PLAYER_NAME = "UPDATE_PLAYER_NAME";
export const UPDATE_PLAYER_HEALTH = "UPDATE_PLAYER_HEALTH";
export const UPDATE_PLAYER_ATTACK = "UPDATE_PLAYER_ATTACK";
export const UPDATE_PLAYER_TOKENS = "UPDATE_PLAYER_TOKENS";